# This is a config for E2B sandbox template.
# You can use template ID (858l5u3vs6ettr70ctvk) or template name (anurag-nextjs-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("anurag-nextjs-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("anurag-nextjs-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('anurag-nextjs-2')

team_id = "c5407d0b-593b-40b4-8e74-4dc050101453"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "anurag-nextjs-2"
template_id = "858l5u3vs6ettr70ctvk"
